# Generated by Django 3.2.13 on 2022-05-23 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_autorized',
            new_name='user_authorized',
        ),
    ]
