# Generated by Django 3.2.13 on 2022-05-21 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Five_w_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('five_w_value', models.CharField(max_length=50)),
                ('five_w_text', models.TextField(blank=True)),
                ('five_w_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='In_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_value', models.CharField(max_length=50)),
                ('pda_01', models.TextField()),
                ('in_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Status_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_value', models.CharField(max_length=50)),
                ('theme_text', models.TextField(blank=True)),
                ('theme_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Totem_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totem_value', models.CharField(max_length=50)),
                ('totem_text', models.TextField(blank=True)),
                ('totem_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Content_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_subject', models.CharField(max_length=255)),
                ('content_reference', models.CharField(blank=True, max_length=255)),
                ('content_creation_date', models.DateField()),
                ('content_comment_01', models.TextField(blank=True, max_length=255)),
                ('content_comment_02', models.TextField(blank=True)),
                ('content_comment_03', models.TextField(blank=True, max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_five_w', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.five_w_table')),
                ('content_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.in_table')),
                ('content_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.status_table')),
                ('content_theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.theme_table')),
                ('content_totem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.totem_table')),
            ],
        ),
    ]
