# Generated by Django 3.2.13 on 2022-06-04 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_base_table_conjunto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_table',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.conjunto_table'),
        ),
        migrations.AlterField(
            model_name='base_table',
            name='content_base',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='conjunto_table',
            name='content_conjunto',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
