# Generated by Django 3.2.13 on 2022-06-04 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220603_2327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base_table',
            old_name='author',
            new_name='content_conjunto',
        ),
    ]
