# Generated by Django 3.2.13 on 2022-06-04 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_base_table_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_table',
            name='author',
        ),
    ]
