# Generated by Django 3.2.13 on 2022-06-26 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0014_sub_base_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turma_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma_name', models.TextField(blank=True)),
                ('turma_genero', models.TextField(blank=True)),
                ('turma_idade', models.TextField(blank=True)),
                ('turma_renda', models.TextField(blank=True)),
                ('turma_status', models.TextField(blank=True)),
                ('turma_o_que_querem', models.TextField(blank=True)),
                ('turma_lista_de_problemas', models.TextField(blank=True)),
                ('turma_em_relacao_ao_PRR', models.TextField(blank=True)),
                ('turma_quando', models.TextField(blank=True)),
                ('turma_como', models.TextField(blank=True)),
                ('turma_onde', models.TextField(blank=True)),
                ('turma_o_que', models.TextField(blank=True)),
                ('turma_quem', models.TextField(blank=True)),
                ('turma_por_que', models.TextField(blank=True)),
                ('turma_dreams_list', models.TextField(blank=True)),
                ('turma_stucks_list', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
