# Generated by Django 3.2.13 on 2022-06-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_turma_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma_table',
            name='turma_genero',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='turma_table',
            name='turma_idade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='turma_table',
            name='turma_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='turma_table',
            name='turma_o_que_querem',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='turma_table',
            name='turma_renda',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='turma_table',
            name='turma_status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
